--1. Script Oracle 19c
--Crear Tabla
CREATE TABLE RESULTADOS_ESTADISTICOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    DATOS VARCHAR2(4000),
    MEDIA NUMBER(10,2),
    MEDIANA NUMBER(10,2),
    MODA NUMBER(10,2),
    VARIANZA NUMBER(10,2),
    DESVIACION NUMBER(10,2),
    MAXIMO NUMBER(10,2),
    MINIMO NUMBER(10,2),
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    CONSTRAINT PK_RESULTADOS PRIMARY KEY(ID)
);

COMMIT;